- name: Setup for devbox distrobox
  hosts: localhost
  become: no
  vars:
    user_id: "{{ ansible_user_id }}"
  tasks:
    - name: Add Microsoft's GPG key for rpm
      become: yes
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
    - name: Copy external repos to /etc/yuom.repos.d
      become: yes
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - { src: cloudflared-ascii.repo, dest: /etc/yum.repos.d/cloudflare.repo }
        - { src: vscode.repo, dest: /etc/yum.repos.d/vscode.repo }
    - name: Install additional packages
      become: yes
      ansible.builtin.dnf:
        name:
          - bat
          - btop
          - cargo
          - cloudflared
          - code
          - direnv
          - fd-find
          - fish
          - fzf
          - gawk
          - git
          - git-delta
          - gnome-keyring
          - keychain
          - neovim
          - pip
          - python3.11
          - python3.12
          - ripgrep
          - wget
          - zoxide
        state: present
    - name: Install ruff via pip
      ansible.builtin.pip:
        name:
          - ruff
    - name: Change user shell to fish
      become: yes
      user:
        name: "{{ user_id }}"
        shell: /usr/bin/fish
    - name: Get starship path to check if it is installed
      shell: 
        cmd: which starship
      args:
        executable: /usr/bin/fish
      register: starship_path
      ignore_errors: true
      changed_when: 
        - starship_path.rc == 1
        - "'which: no starship' in starship_path.stderr"
    - name: Install starship if no path
      become: yes
      ansible.builtin.shell:
        cmd: curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
      when: starship_path is not defined or starship_path.stdout is not defined or starship_path.stdout == ''
    - name: Get fisher path to check if it is installed
      shell: 
        cmd: fisher
      args:
        executable: /usr/bin/fish
      register: fisher_path
      ignore_errors: true
      changed_when: 
        - fisher_path.rc == 1
        - "'fish: Unknown command: fisher' in fisher_path.stderr"
    - name: Install fisher if no path
      ansible.builtin.shell:
        cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher jorgebucaran/nvm.fish
      args:
        executable: /usr/bin/fish
      when: fisher_path is not defined or fisher_path.stdout is not defined or fisher_path.stdout == ''
    - name: Export VS code for rofi access
      ansible.builtin.shell:
        cmd: distrobox-export --app code
    - name: Get uv path to check if it is installed
      shell: 
        cmd: uv
      args:
        executable: /usr/bin/fish
      register: uv_path
      ignore_errors: true
      changed_when: 
        - uv_path.rc == 1
        - "'fish: Unknown command: uv' in uv_path.stderr"
    - name: Install uv if no path
      ansible.builtin.shell:
        cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        executable: /usr/bin/fish
      when: uv_path is not defined or uv_path.stdout is not defined or uv_path.stdout == ''
    - name: Create symbolic links for distrobox-host-exec to access tools outside the devbox
      become: yes
      ansible.builtin.file:
        src: /usr/bin/distrobox-host-exec
        dest: "{{ item }}"
        state: link
      loop:
        - /usr/local/bin/docker
        - /usr/local/bin/docker-compose
        - /usr/local/bin/kitten
        - /usr/local/bin/kitty
        - /usr/local/bin/podman
        - /usr/local/bin/podman-compose
        - /usr/local/bin/xdg-open
