- hosts: localhost
  tasks:
    - name: Remove default Firefox with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - firefox
          - firefox-langpacks
        state: absent
    - name: Layer required packages with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - bat
          - btop
          - distrobox
          - fastfetch
          - fd-find
          - fish
          - git-delta
          - keychain
          - kitty
          - kitty-kitten
          - neovim
          - podman-compose
          - ripgrep
          - zoxide
        state: present
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install packages from flathub
      community.general.flatpak:
        name:
          - com.logseq.Logseq
          - com.transmissionbt.Transmission
          - io.itch.itch
          - md.obsidian.Obsidian
          - org.gimp.GIMP
          - org.gnome.Evince
          - org.gnome.Papers
          - org.inkscape.Inkscape
          - org.kde.yakuake
          - org.mozilla.firefox
          - org.onlyoffice.desktopeditors
