- name: Local settings
  hosts: localhost
  become: no
  vars:
    user_id: "{{ ansible_user_id }}"
  tasks:
    - name: Change user shell to fish
      become: yes
      user:
        name: "{{ user_id }}"
        shell: /usr/bin/fish
    - name: Get starship path to check if it is installed
      shell: 
        cmd: which starship
      args:
        executable: /usr/bin/fish
      register: starship_path
      ignore_errors: true
      changed_when: 
        - starship_path.rc == 1
        - "'which: no starship' in starship_path.stderr"
    - name: Install starship if no path
      become: yes
      ansible.builtin.shell:
        cmd: curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
      when: starship_path == ''
    - name: Get fisher path to check if it is installed
      shell: 
        cmd: fisher
      args:
        executable: /usr/bin/fish
      register: fisher_path
      ignore_errors: true
      changed_when: 
        - fisher_path.rc == 1
        - "'fish: Unknown command: fisher' in fisher_path.stderr"
    - name: Install fisher if no path
      ansible.builtin.shell:
        cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher catppuccin/fish
      args:
        executable: /usr/bin/fish
      when: fisher_path == ''
    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
      loop:
        - { path: ~/.config, mode: "0700" }
        - { path: ~/.config-devbox, mode: "0700" }
        - { path: ~/.local/share/flatpak/overrides, mode: "0755" }
        - { path: ~/.local/share/fonts/JetBrainsMono, mode: "0755" }
        - { path: ~/.local/share/fonts/JetBrainsMonoNerdFont, mode: "0755" }
        - { path: ~/.local/share/fonts/NerdFontsSystemOnly, mode: "0755" }
        - { path: ~/Workspace, mode: "0755" }
    - name: Clone my dotfile git repository
      ansible.builtin.git:
        repo: git@github.com:ufeindt/dotfiles.git
        dest: ~/Workspace/dotfiles
    - name: Create symbolic links to my dotfiles
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { src: ~/Workspace/dotfiles/config/dunst, dest: ~/.config/dunst }
        - { src: ~/Workspace/dotfiles/config/fish, dest: ~/.config/fish }
        - { src: ~/Workspace/dotfiles/config/kitty, dest: ~/.config/kitty }
        - { src: ~/Workspace/dotfiles/config/nvim, dest: ~/.config/nvim }
        - { src: ~/Workspace/dotfiles/config/rofi, dest: ~/.config/rofi }
        - { src: ~/Workspace/dotfiles/config/starship.toml, dest: ~/.config/starship.toml }
        - { src: ~/Workspace/dotfiles/config/sway, dest: ~/.config/sway }
        - { src: ~/Workspace/dotfiles/config/swaylock, dest: ~/.config/swaylock }
        - { src: ~/Workspace/dotfiles/config/waybar, dest: ~/.config/waybar }
    - name: Download fonts
      ansible.builtin.unarchive:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip, dest: ~/.local/share/fonts/JetBrainsMono }
        - { src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/NerdFontsSymbolsOnly.zip, dest: ~/.local/share/fonts/NerdFontsSystemOnly }
        - { src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip, dest: ~/.local/share/fonts/JetBrainsMonoNerdFont }
    - name: Git config
      git_config:
        name: user.name
        scope: global
        value: Ulrich Feindt
      loop:
        - { name: core.editor, value: nvim }
        - { name: user.name, value: Ulrich Feindt }
        - { name: user.email, value: ufeindt@gmail.com }
        - { name: push.autoSetRemote, value: true }
    - name: Set gnome setting to prefer dark color schemes
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
    - name: Copy Flatpak global overrides
      ansible.builtin.copy:
         src: flatpak-global-overrides
         dest: ~/.local/share/flatpak/overrides/global
         mode: '0644'
    - name: Create dev distrobox
      ansible.builtin.shell: 
        cmd: distrobox create -Y --name devbox --image fedora:40 --additional-packages ansible
      args:
        executable: /usr/bin/fish
