- hosts: localhost
  tasks:
    - name: Remove default Firefox with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - firefox
          - firefox-langpacks
        state: absent
    - name: Layer required packages with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - distrobox
          - docker
          - docker-compose
          - eza
          - fastfetch
          - fish
          - kitty
          - kitty-kitten
          - neovim
        state: present
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install package from flathub
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - org.gtk.Gtk3theme.Adwaita-dark
          - org.chromium.Chromium
          - com.vivaldi.Vivaldi
          - com.github.tchx84.Flatseal
          - com.discordapp.Discord
          - rest.insomnia.Insomnia
          - com.logseq.Logseq
          - md.obsidian.Obsidian
          - com.slack.Slack
          - org.flameshot.Flameshot
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - io.dbeaver.DBeaverCommunity
          - com.valvesoftware.Steam
          - org.gnome.Evince
          - org.gimp.GIMP
          - org.inkscape.Inkscape
    - name: Set flatpak env var for the Firefox GTK theme
      ansible.builtin.command:
        argv:
          - flatpak
          - override
          - --user
          - --env=GTK_THEME=Adwaita:dark
          - org.mozilla.firefox
    - name: Set flatpak env var for setting Firefox to prefer dark themes
      ansible.builtin.command:
        argv:
          - flatpak
          - override
          - --user
          - --env=ADW_DEBUG_COLOR_SCHEME=prefer-dark 
          - org.mozilla.firefox
    - name: Set git editor to neovim
      git_config:
        name: core.editor
        scope: global
        value: nvim
    - name: Set git user name
      git_config:
        name: user.name
        scope: global
        value: Ulrich Feindt
    - name: Set git user email
      git_config:
        name: user.email
        scope: global
        value: ufeindt@gmail.com
    - name: Set git to set upstream branch automatically
      git_config:
        name: push.autoSetRemote
        scope: global
        value: true

