- hosts: localhost
  tasks:
    - name: Remove default Firefox with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - firefox
          - firefox-langpacks
        state: absent
    - name: Layer required packages with rpm-ostree
      community.general.rpm_ostree_pkg:
        name: 
          - bat
          - btop
          - distrobox
          - eza
          - fastfetch
          - fd-find
          - fish
          - fzf
          - git-delta
          - keychain
          - kitty
          - kitty-kitten
          - neovim
          - podman-compose
          - ripgrep
          - swappy
          - zoxide
        state: present
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install packages from flathub
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - com.logseq.Logseq
          - com.slack.Slack
          - com.transmissionbt.Transmission
          - com.vivaldi.Vivaldi
          - io.dbeaver.DBeaverCommunity
          - md.obsidian.Obsidian
          - org.chromium.Chromium
          - org.gimp.GIMP
          - org.gnome.Evince
          - org.gtk.Gtk3theme.Adwaita-dark
          - org.inkscape.Inkscape
          - org.mozilla.firefox
          - org.onlyoffice.desktopeditors
          - org.videolan.VLC
