- hosts: localhost
  become: no
  tasks:
    - name: Get starship path to check if it is installed
      shell: 
        cmd: which starship
      args:
        executable: /usr/bin/fish
      register: starship_path
      ignore_errors: true
      changed_when: 
        - starship_path.rc == 1
        - "'which: no starship' in starship_path.stderr"
    - name: Install starship if no path
      become: yes
      ansible.builtin.shell:
        cmd: curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
      when: starship_path == ''
    - name: Get fisher path to check if it is installed
      shell: 
        cmd: which fisher
      args:
        executable: /usr/bin/fish
      register: fisher_path
      ignore_errors: true
      changed_when: 
        - fisher_path.rc == 1
        - "'which: no fisher' in fisher_path.stderr"
    - name: Install fisher if no path
      ansible.builtin.shell:
        cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher catppuccin/fish
      args:
        executable: /usr/bin/fish
      when: fisher_path == ''
    
