#!/bin/bash

notify-send "Starting updates"

notify-send "Updating RPM packages"
rpm-ostree update
notify-send "Finished updating RPM packages"

notify-send "Updating Flatpak packages"
flatpak update -y
notify-send "Finished updating Flatpak packages"

notify-send "Updating dnf packages in devbox"
distrobox enter devbox -e sudo dnf update -y
notify-send "Finished updating dnf packages in devbox"

notify-send "Updates complete. Please restart your computer at you convenience." -t 0
